
defaults:
  expname: basis_room_real_mask
  logdir: ./logs

  ckpt: null                  # help='specific weights npy file to reload for coarse network'

model:
  basis_dims: [5,5,5,2,2,2]
  basis_resos: [ 64,  83, 102, 121, 140, 160]
  coeff_reso: 16
  coef_init: 0.01
  phases: [0.0]

  coef_mode: bilinear
  basis_mode: bilinear

  freq_bands: [ 1.0000, 1.7689, 2.3526, 3.1290, 4.1616, 6.]

  kernel_mapping_type: 'sawtooth'

  in_dim: 3
  out_dim: 32
  num_layers: 2
  hidden_dim: 128

dataset:
  # loader options
  dataset_name: llff # choices=['blender', 'llff', 'nsvf', 'dtu','tankstemple', 'own_data']
  datadir: /home/anpei/code/NeuBasis/data/360_v2/room/
  ndc_ray: 0
  is_unbound: True

  with_depth: 0
  downsample_train: 4.0
  downsample_test: 4.0

  N_vis: 5
  vis_every: 5000

training:

  n_iters: 30000
  batch_size: 4096

  volume_resoInit: 128 # 128**3：
  volume_resoFinal: 320 # 300**3

  upsamp_list: [2000,3000,4000,5500]
  update_AlphaMask_list: [2500]
  shrinking_list: [-1]

  L1_weight_inital: 0.0
  L1_weight_rest: 0.0

  TV_weight_density: 0.0
  TV_weight_app: 0.00

exporation:
  render_only: 0
  render_test: 1
  render_train: 0
  render_path: 0
  export_mesh: 0
  export_mesh_only: 0

renderer:
  shadingMode: MLP_Fea
  num_layers: 3
  hidden_dim: 128

  fea2denseAct: 'relu'
  density_shift: -10
  distance_scale: 25.0

  view_pe: 6
  fea_pe: 2

  lindisp: 0
  perturb: 1          # help='set to 0. for no jitter, 1. for jitter'

  step_ratio: 0.5
  max_samples: 1600

  alphaMask_thres: 0.04
  rayMarch_weight_thres: 1e-3










